### ISSUE TITLE
furion support CONNECT method ?

### ISSUE THREAD

**Issue by ingnelson** [keli/furion#1]
Hello sir.

I would like your help and i am glad to pay you for your service.

1) I am behind a firewall

 2) The client is a Android Application, it can sends an HTTP request with the proxy and then to the SSH server to create the tunnel.

3) On the internet I found the following:
 HTTP proxy: 50.18.211.227:8043
 Fully qualified domain name (FQDN): 5ef50094901b6f5fccdfd0f6-172-245-22-211.cloudmi.datami.net

The proxy is linked to their domain, the only thing that altered was the domain which removed their IP that it had and put or added mine 172-245-22-211 so that your proxy will not reject the connection.

I show you the connection that WIRESHARK shows me. What you send and what you receive :

![Tunnel1](https://user-images.githubusercontent.com/6626845/86406195-e950cd80-bc6f-11ea-831e-9354405d4ccf.jpg)
![Tunnel2](https://user-images.githubusercontent.com/6626845/86406203-eb1a9100-bc6f-11ea-9db5-0d6d7c572f97.jpg)

It is possible to create a proxy that support CONNECT method and support HTTPS or SSL  like that proxy I found on the internet  ? 

The proxy 50.18.211.227:8043  response is :

HTTP/1.1 200 Connection established.
Server: sdgw

then goes the response from my SSH dropbear on port 443 and the tunnel is created.

i want a proxy like that on my VPS .

I am going to wait for your reply.

**Comment by keli** [comment]
Hi there,

Is it that you want to use Furion to bypass the firewall which allows only HTTP/HTTPS traffic?

If you do have a VPS, this can be done by setting up a Furion server on 443 port of your VPS with SSL enabled, and an extra local HTTP proxy which supports using local Furion socks5 port as a parent proxy (Polipo would be an example), if your client only supports HTTP proxy.

But considering the client is Android, there are more mobile friendly and efficient solutions available. Even I myself only use Furion to bootstrap or as a last resort when other popular solutions are prohibited. Other solutions like shadowsocks/v2ray/trojan all have many Android clients support and you can use third-party service providers if you don't mind paying. I think those might worth investigating in your case.

Hope this helps.

**Comment by keli** [comment]
Oh and of course you can just straight up install Polipo on your VPS and enable access control, which would probably be the simplest.

**Comment by ingnelson** [comment]
@keli  I like the idea that you said using polipo on port  and then  furion on port 443 , I will try myself first , but if I can not do it , can I send you my VPS and you can install it  for me ?

Note: I tried shadowsocks, V2RAY , trojan but the problem those project do not have the option to modify the http request (add my own http headers ) , that is the reason I use "http injector " app on android , where I can edit or add the method and the http headers that I want .

**Comment by keli** [comment]
@ingnelson I'm still not entirely certain what you're trying to achieve here, with the above mentioned projects, their android clients basically just provide VPN service to you android and shouldn't affect application level protocols like HTTP.

I just pushed a new version so that you can use 443 as non-root user with systemd. I've only tested on python3 though. If you want to install a server, see if the following bash function works for you:

```bash
function setup_furion_server {
    pip3 install -U furion
    useradd --system furion
    mkdir /etc/furion /var/log/furion

    openssl req \
        -x509 -nodes -days 3650 \
        -subj "/C=US/ST=CA/L=LA/CN=furion.org" \
        -newkey rsa:2048 -keyout /etc/furion/furion.pem -out /etc/furion/furion.pem

    cat > /etc/furion/furion.cfg <<END
[main]
local_ip = 0.0.0.0
local_port = 443
with_systemd = on
local_ssl = on
pem_path = furion.pem
local_auth = on
allowed_ports = all
ping_server = on
dns_server = off
log_level = 20
log_path = /var/log/furion/furion.log

[plugin]
auth_plugin = simpleauth

[simpleauth]
password_path = simpleauth.passwd
END

    echo 'username password' > /etc/furion/simpleauth.passwd

    cat > /etc/systemd/system/furion.service <<END
[Unit]
Description=Furion Service
Requires=furion.socket
After=network.target

[Service]
Type=simple
Restart=always
RestartSec=1
User=furion
Group=furion
ExecStart=/usr/local/bin/furion

[Install]
WantedBy=multi-user.target
END
    cat > /etc/systemd/system/furion.socket <<END
[Unit]
Description=Furion socket

[Socket]
ListenStream=443
NoDelay=true
END

    chown -R furion.furion /etc/furion /var/log/furion
    systemctl enable furion.service
    systemctl start furion.service
}

setup_furion_server
```

To configure a client basically you just need a /etc/furion/furion.cfg and a /etc/furion/upstream.json to store server information, look into [examples directory](https://github.com/keli/furion/tree/master/examples) to get some ideas.
